name: Build ImmortalWrt

on:
  workflow_dispatch:  # 允许手动触发
  push:
    branches:
      - master  # 可根据需要修改分支

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新版Ubuntu运行环境

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置Ubuntu环境依赖
        run: |
          sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.org/init_build_environment.sh)'

      - name: 克隆ImmortalWrt仓库
        run: |
          git clone --single-branch --filter=blob:none -b openwrt-24.10 https://github.com/immortalwrt/immortalwrt

      - name: 更新并安装feeds
        run: |
          cd immortalwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: 复制配置文件
        run: |
          cp .config immortalwrt/

      - name: 编译固件
        id: compile
        run: |
          cd immortalwrt
          # make -j$(nproc)
          make -j1

      - name: Upload bin directory
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt_bin
          path: immortalwrt/bin
