name: Build ImmortalWrt

on:
  workflow_dispatch:  # 允许手动触发
  push:
    branches:
      - master  # 可根据需要修改分支

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新版Ubuntu运行环境

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: true

          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true

      - name: 清理磁盘空间
        run: |
         sudo rm -rf /opt/ghc
         sudo rm -rf "/usr/local/share/boost"
         sudo rm -rf "$AGENT_TOOLSDIRECTORY"
         sudo apt clean
         df -h

      - name: 设置Ubuntu环境依赖
        run: |
          sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.org/init_build_environment.sh)'

      - name: 克隆ImmortalWrt仓库
        run: |
        working-directory: /mnt
          git clone --single-branch --filter=blob:none -b openwrt-23.05 https://github.com/immortalwrt/immortalwrt

      - name: 更新并安装feeds
        run: |
        working-directory: /mnt/immortalwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: 复制配置文件
        run: |
          cp .config /mnt/immortalwrt/

      - name: 编译固件
        id: compile
        working-directory: /mnt/immortalwrt
        run: |
          make defconfig
          make download -j$(nproc)
          make -j1

      - name: Upload bin directory
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt_bin
          path: /mnt/immortalwrt/bin


      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 2

      - name: Remove old Releases
        uses: dev-drprasad/delete-older-releases@master
        with:
          keep_latest: 3
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
