name: Build ImmortalWrt

on:
  workflow_dispatch:  # 允许手动触发
  push:
    branches:
      - master  # 可根据需要修改分支

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新版Ubuntu运行环境

    steps:


      - name: 释放空间开始
        run: |
          echo "Before freeing up disk space"
          echo "=============================================================================="
          df -hT
          echo "=============================================================================="

      - name: 优化空间
        uses: "hugoalh/disk-space-optimizer-ghaction@v0.8.1"
        with:
          operate_sudo: "True"
          general_include: ".+"
          general_exclude: |-
            ^GCC$
            ^G\+\+$
            Clang
            LLVM
          docker_include: ".+"
          docker_prune: "True"
          docker_clean: "True"
          apt_prune: "True"
          apt_clean: "True"
          homebrew_prune: "True"
          homebrew_clean: "True"
          npm_prune: "True"
          npm_clean: "True"
          os_swap: "True"

      - name: 整合释放空间
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 2048
          swap-size-mb: 1
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: 释放空间完成
        run: |
          echo "Free up disk space complete"
          echo "=============================================================================="
          df -hT
          echo "=============================================================================="

      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置Ubuntu环境依赖
        run: |
          sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.org/init_build_environment.sh)'

      - name: 克隆ImmortalWrt仓库
        run: |
          git clone --depth=1 --single-branch --filter=blob:none -b openwrt-23.05 https://github.com/immortalwrt/immortalwrt

      - name: 更新并安装feeds
        run: |
        working-directory:
          cd immortalwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: 复制配置文件
        run: |
          cp .config /mnt/immortalwrt/

      - name: 编译固件
        id: compile
        run: |
          cd immortalwrt
          make defconfig
          make download -j$(nproc)
          make -j1

      - name: 上传固件
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt_bin
          path: immortalwrt/bin


      - name: 删除workflow运行
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 2

      - name: 移除旧Release
        uses: dev-drprasad/delete-older-releases@master
        with:
          keep_latest: 3
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
